name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cabal:

    # libfuse3 requires ubuntu>=20.04
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: ['8.8.4', '8.10.7', '9.0.2', '9.2.4', '9.4.2']
        cabal: ['3.6.2.0']

      fail-fast: false

    steps:
    - name: Install libfuse3
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse3-dev fuse3

    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build
      run: |
        autoreconf -fiv
        cabal v2-update
        # Compile the sdist archive instead of the source tree to make sure the all required files are packaged in it
        cabal v2-sdist
        tar -xf dist-newstyle/sdist/libfuse3-*.tar.gz
        cd libfuse3-*/
        cabal v2-configure --flags=examples --enable-tests --enable-documentation
        cabal v2-build all
        cabal v2-haddock

    - name: Run tests
      run: |
        cabal v2-run -- unittest
        cabal v2-run -- integtest

  stack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.0.2']
        stack: ['2.7.5']
      fail-fast: false

    steps:

    - name: Install libfuse3
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse3-dev fuse3

    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      name: Setup Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Install dependencies
      run: |
        stack build --system-ghc --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack build --system-ghc --no-run-tests --no-run-benchmarks

    - name: Run tests
      run: |
        stack test --system-ghc