name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # also run every Sunday in attempt to detect out-of-date version bounds
  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:

    # libfuse3 requires ubuntu>=20.04
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ghc: ['8.4.4', '8.6.5', '8.8.4', '8.10.3']
        cabal: ['3.4.0.0']

      fail-fast: false

    steps:
    - name: Install libfuse3
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse3-dev fuse3

    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Check version bounds
      run: cabal outdated --exit-code

    - name: Build
      run: |
        autoreconf -fiv
        cabal v2-update
        # Compile the sdist archive instead of the source tree to make sure the all required files are packaged in it
        cabal v2-sdist
        tar -xf dist-newstyle/sdist/libfuse3-*.tar.gz
        cd libfuse3-*/
        cabal v2-configure --flags=examples --enable-tests --enable-documentation
        # avoid building the documentations of the certain dependencies with ghc-8.4 because it crashes haddock
        case "$(ghc --numeric-version)" in
          8.4*)
            echo ''                       >> cabal.project.local
            echo 'package aeson'          >> cabal.project.local
            echo '  documentation: False' >> cabal.project.local
            echo 'package vector'         >> cabal.project.local
            echo '  documentation: False' >> cabal.project.local
            ;;
          *)
            ;;
        esac
        cabal v2-build all
        cabal v2-haddock

    - name: Run tests
      run: |
        cabal v2-run -- unittest
        cabal v2-run -- integtest
